[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mstcvi"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "matplotlib",
    "quitefastmst",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "ipykernel",
    "clustering-benchmarks",
]